// ... (previous code)
// Scheduled maintenance data
const maintenanceRecords = [
  {
    id: "M001",
    vehicleId: "FL-001",
    type: "Oil Change",
    status: "Scheduled",
    scheduledDate: "2024-03-15",
    estimatedCost: 150,
    priority: "Medium",
    description: "Regular oil change and filter replacement",
    maintenanceType: "scheduled",
  },
  {
    id: "M002",
    vehicleId: "FL-002",
    type: "Brake Inspection",
    status: "Overdue",
    scheduledDate: "2024-03-01",
    estimatedCost: 300,
    priority: "High",
    description: "Brake pad inspection and replacement if needed",
    maintenanceType: "scheduled",
  },
  {
    id: "M003",
    vehicleId: "FL-003",
    type: "Tire Rotation",
    status: "Completed",
    scheduledDate: "2024-02-28",
    estimatedCost: 80,
    priority: "Low",
    description: "Tire rotation and pressure check",
    maintenanceType: "scheduled",
  },
  {
    id: "M004",
    vehicleId: "FL-004",
    type: "Engine Diagnostic",
    status: "In Progress",
    scheduledDate: "2024-03-10",
    estimatedCost: 200,
    priority: "High",
    description: "Engine diagnostic and tune-up",
    maintenanceType: "scheduled",
  },
  {
    id: "M005",
    vehicleId: "FL-005",
    type: "AC Service",
    status: "Scheduled",
    scheduledDate: "2024-03-20",
    estimatedCost: 120,
    priority: "Medium",
    description: "Air conditioning system service and refrigerant check",
    maintenanceType: "scheduled",
  },
  {
    id: "M006",
    vehicleId: "FL-006",
    type: "General Inspection",
    status: "Scheduled",
    scheduledDate: "2024-03-25",
    estimatedCost: 250,
    priority: "Medium",
    description: "Annual vehicle inspection",
    maintenanceType: "scheduled",
  },
];
// ... (rest of the file)